### PR TITLE
Combine multiple remediations

### PR DESCRIPTION
**Pull request by Salipa-Gurung**
### Description

Previously remediations of vulnerability were not appended (only last remediation was stored). 
So, this pr combines `details` of all the remediations (regardless of the category: mitigation, no_fix_planned, none_available, vendor_fix, workaround) of a vulnerability and sets it in `remediations` key.

Upstream pr: https://github.com/anthonyharrison/csaf/pull/6

### CODE REVIEW

**Comment by individual-it** [comment]
is there also the same PR upstream?

**Comment by Salipa-Gurung** [comment]
No, we haven't created upstream pr about remediations yet. There's an issue about it https://github.com/anthonyharrison/csaf/issues/3

**Comment by individual-it** [comment]
please create one, the goal is not to keep this fork, but at some point to go back to the original library.
Please also link the upstream PR here

**Comment by S-Panta** [comment]
LGTM.

**Review by S-Panta — APPROVED** [review]

**Review by individual-it — APPROVED** [review]

**Pull request merged**
